import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/block/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getData = async () => {
  const res = await fetch(`${otherUrl}/settings/`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error("Something went wrong");
  }
  return res.json();
};

export default async function RootLayout({ children }) {
  const settingsData = await getData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar data={settingsData.main_menu} />
        {children}
      </body>
    </html>
  );
}
